### ISSUE TITLE
please answer me [urgent]

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [ahmedsamirio/olx-car-ad-scraper#1]
hello sir i have tried your project and print all the time this line finished ad addict 

and after i stop the script and try to find the csv file on my computer didnt get it can u help me please i need this project very important 
@ahmedsamirio

**Comment by ahmedsamirio** [comment]
Hello Ahmed,

Could you please tell me exactly how you ran the script?  And if you have changed anything in the `config.py` file? 

It would also be really helpful if your copied the output of what you ran.

Regards,
Ahmed Samir

**Comment by ahmedabdelhamedz** [comment]
this is the output appear to me and this line is reapeated with no end until i stopped the script 

output : finished ad dicts

i run this script download all the files 

__pycache__
README.md
config.py
scraper.py
test_batch_time

in the path that all my python scripts on it is this path 


C:\Users\ahmedabdelhamed\PycharmProjects\pythonProject

the file that i run is scraper.py and i dont change anything in the config 

thanks to u for quick reply 
@ahmedsamirio

**Comment by ahmedsamirio** [comment]
Okay so you run `scraper.py` script in the windows command line using python, am I right?

And if so, what is the output after you run the script?

**Comment by ahmedabdelhamedz** [comment]
yes you are right but i run it through picharm after i run the script 

this is the output:  finished ad dicts 

this output is reapted every second dont stop until i stopped the script 

but no csv created on my computer to check the info that scrapped

**Comment by ahmedsamirio** [comment]
Okay I think I have found the problem.

It seems that I have left a print statement when each ad has finished scraping, you can find it in line 75 in `scraper.py` 
```
    print("Finished ad dict")
```
Just comment this line and it shall be working just fine. You should expect a print statement for each mini-batch scraped. The `batch_count` parameter is present in the `config.py` file if you want to play with it. Using the current configuration parameters, you should expect to finish scraping in 25 mini-batches (500 pages divided in 20 page mini-batch).

So run the script and keep checking the printed statements every once in a while and you should see
```
Finished mini-batch 1  
Finished mini-batch 2
....
```

Then finally 
```
The scraped data was succesfully converted into olx_raw.csv
```
Good luck.

**Comment by ahmedabdelhamedz** [comment]
i tried to comment the line 75     #print("Finished ad dict")

i got this error 

Exception in thread Thread-261:
Traceback (most recent call last):
  File "C:\Users\ahmedabdelhamed\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\ahmedabdelhamed\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ahmedabdelhamed\PycharmProjects\pythonProject\scraper.py", line 146, in scrape_ad
    ad_dict = make_ad_dict(link_soup, link)
  File "C:\Users\ahmedabdelhamed\PycharmProjects\pythonProject\scraper.py", line 73, in make_ad_dict
    ad_dict['Chasis'] = get_info_from_id('نوع الهيكل', ad_info, ad_info_ids)
  File "C:\Users\ahmedabdelhamed\PycharmProjects\pythonProject\scraper.py", line 30, in get_info_from_id
    return full_info[info_idx]
IndexError: list index out of range


when i try to change the print to print(all_ad_dicts)

it get the ads on the output 

i want to know how to solve this error and what to write on print in line 75 to show me every Finished mini-batch 1  

I appreciate your patience 

@ahmedsamirio

**Comment by ahmedsamirio** [comment]
This error is due to an that didn't fit in how the scraper works, and it should continue scraping other ads nonetheless even it showed you this error.
Just run the script and leave it running. Don't add that print statement of all_ad_dicts as it's useless.
I preferred to leaved the `print("Finished ad dict")` as it showed me that the threads of the scraper continued even if an error like the one you had was raised, so you could leave it if you want.
Anyways, leave the script running and don't close it.

**Comment by ahmedabdelhamedz** [comment]
i am sorry for your Disturbance mr ahmed i am just new to the programming and python language but i need this on my work 

i run the script as you told me it end on Finished mini-batch 25 

but when i open the file that the script created all the data that in arabic language appear on understandable language 

like this 


ظ…ط±ط³ظٹط¯ط³   ط¨ظ†ط² | ط¥ط³ 500 | ط§ظ„ط¬ظٹط²ط© | 6 ط£ظƒطھظˆط¨ط± | 5 ظٹظˆظ„ظٹظˆ 2021 | ظ¢ظ ظ¢ظ، | ظ  ط¥ظ„ظ‰ ظ©ظ©ظ©ظ© | ظƒط§ط´ | ظ…ط¹ط±ظˆط¶ ظ„ظ„ط¨ظٹط¹ | ط§ظˆطھظˆظ…ط§طھظٹظƒ | ط£ظƒط«ط± ظ…ظ†   ظ£ظ ظ ظ | ط³ظٹط¯ط§ظ† |   | ط£ط³ظˆط¯ | 4500 | 



if i want to scrape another category on olx what i add to the script to can scrape mobile number , ad title , ad description and name of ad owner 

at all thanks for your support

@ahmedsamirio
